---

  - name: Add apt repository
    apt_repository: repo='{{ item }}'
    with_items:
     - deb http://archive.ubuntu.com/ubuntu/ trusty main restricted
     - deb http://archive.ubuntu.com/ubuntu/ trusty-updates main restricted
     - deb http://archive.ubuntu.com/ubuntu/ trusty universe
     - deb http://archive.ubuntu.com/ubuntu/ trusty-updates universe
     - deb http://archive.ubuntu.com/ubuntu/ trusty multiverse
     - deb http://archive.ubuntu.com/ubuntu/ trusty-updates multiverse
     - deb http://archive.ubuntu.com/ubuntu/ trusty-backports main restricted universe multiverse
     - deb http://security.ubuntu.com/ubuntu trusty-security main restricted
     - deb http://security.ubuntu.com/ubuntu trusty-security universe
     - deb http://security.ubuntu.com/ubuntu trusty-security multiverse

  - name: Install Packages
    apt: name={{ item }} update_cache=yes
    with_items:
     - apache2
     - libapache2-modsecurity

  - name: Enable apache modules
    apache2_module:  name={{ item }}
    with_items:
     - ssl
     - proxy
     - proxy_http

