---

  - name: create-directories
    shell: mkdir -p {{ item }}
    with_items:
     - /etc/apache2/ssl/crt

  - name: copy-ssl-certs
    copy: src={{ item.name }} dest={{ item.dest }} owner=root group=root mode=700
    with_items:
     - { name: 'ssl-cert-snakeoil.pem', dest: '/etc/ssl/certs/ssl-cert-snakeoil.pem' }
     - { name: 'ssl-cert-snakeoil.key', dest: '/etc/ssl/private/ssl-cert-snakeoil.key'}

  - name: deploy-conf
    template: src={{ item.tpl }} dest={{ item.file }} backup=yes
    with_items:
     - { tpl: 'site.conf.j2', file: '/etc/apache2/sites-available/default-ssl' }
     - { tpl: 'ports.conf.j2', file: '/etc/apache2/ports.conf' }
     - { tpl: 'httpd.conf.j2', file: '/etc/apache2/httpd.conf'}
    notify: reload apache2  
