- hosts: apacheproxy

  tasks:
  - name: create-directories
    shell: mkdir -p {{ item }}
    with_items:
     - /etc/apache2/ssl/crt

  - name: copy-ssl-certs
    copy: src=files/{{ item.name }} dest={{ item.dest }} owner=root group=root mode=400
    with_items:
     - { name: 'android.swift.crt', dest: '/etc/apache2/ssl/crt/android.swift.crt' }

  - name: deploy-conf
    template: src=templates/{{ item.tpl }} dest={{ item.file }} backup=yes
    with_items:
     - { tpl: 'apache/site_pub.conf.j2', file: '/etc/apache2/sites-available/defautl-ssl' }
 
